name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: main
          
  deploy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: build
        uses: actions/setup-node@master
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: main
          publish_dir: ./dist
          github_token: ${{ secrets.DEVOPS_FRONTEND }}
          commit_message: 自动部署
