name: Deploy

on:
  workflow_dispatch:
      
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
     - name: Step1
       run: echo "这是job1的第一个步骤"
     - name: Step2 
       run: echo "这是job1的第二个步骤"

